apiVersion: v1
description: Prometheus SNMP Exporter
name: prometheus-snmp-exporter
version: 1.6.1
appVersion: v0.23.0-rc.1
home: https://github.com/prometheus/snmp_exporter
sources:
  - https://github.com/prometheus/snmp_exporter
keywords:
  - prometheus
  - snmp
  - monitoring
maintainers:
  - name: miouge1
    email: maxime@root314.com
  - name: xiu
    email: github@xiu.io
  - name: tuc
    email: github@t-b-o-h.com
